[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ml-docker-demo"
version = "0.1"
description = "Simple ML training on Docker demo"
dependencies = ["pyyaml"]