services:
  scheduler:
    image: daskdev/dask:latest
    command: dask-scheduler
    ports:
      - "8786:8786" # scheduler RPC
      - "8787:8787" # dashboard
  worker1:
    image: daskdev/dask:latest
    command: dask-worker tcp://scheduler:8786 --nthreads 1
    depends_on:
      - scheduler
  worker2:
    image: daskdev/dask:latest
    command: dask-worker tcp://scheduler:8786 --nthreads 1
    depends_on:
      - scheduler
