paths:
  data_path: ../../data/train.csv
  model_out: ../../models/model.joblib

mlflow:
  experiment_name: "mlops-demo"

target_col: "target"

train:
  test_size: 0.2
  seed: 42

model:
  n_estimators: 50
  